name: Run tests on any event


on:
  push:
    tags:
      - '*'
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: my_host
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'
          architecture: 'x64'
      - name: Install express
        run: npm install express --save
      - name: Install SQLite
        run: npm install sqlite3