name: Publish on Docker Hub

on:
  push:
    branches:
      - "main"

jobs:
  # build:
  #   needs: [run_tests]
  #   runs-on: self-hosted
  #   steps:
  #     # - name: Checkout
  #     #   uses: actions/checkout@v3

  #     # - name: Set up Docker Buildx
  #       # uses: docker/setup-buildx-action@v2
  #     # - name: Build and push
  #     #   uses: docker/build-push-action@v3
  #     #   with:
  #     #     context: .
  #     #     file: ./Dockerfile
  #     #     push: true
  #     #     tags: ${{ secrets.DOCKER_LOGIN }}/calendar:latest
  post:
    runs-on: self-hosted
    steps:
    - name: delete folder
      run: rm -r calendar
    - name: copy file 
      run: git clone https://github.com/lenochcados/calendar.git
    - name: cd calendar
      run: cd calendar/
    # - name: Delete docker container
    #   run: docker kill $(docker ps -q)
    # - name: Delete docker image
    #   run: docker image prune
    # - name: Docker clean
      # run: docker system prune -a
    # - name: sudo
    #   run: sudo su
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PWD}}  
    # - uses: actions/checkout@v1
    # - name: Login to DockerHub Registry
    #   run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - name: docker build
      run:  docker build ~/actions-runner/_work/calendar/calendar/calendar -t lenochcados/calendar
    - name: docker run
      run: docker run -d -p 80:3000 lenochcados/calendar