name: Publish on Docker Hub

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: my_host
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_LOGIN }}/calendar:latest

  post:
    needs: [build]
    runs-on: my_host
    steps:
    # - name: to port
    #   run: sudo ssh -i ~/.ssh/id_rsa 5.181.252.251
    - name: delete folder
      run: rmdir calendar
    - name: copy file 
      run: git clone https://github.com/lenochcados/calendar.git
    - name: cd calendar
      run: cd calendar/
    # - name: Delete docker container
    #   run: docker kill $(docker ps -q)
    # - name: Delete docker image
    #   run: docker image prune
    - name: docker build
      run: docker build . -t lenochcados/calendar
    - name: docker run
      run: docker run -d -p 80:3000 lenochcados/calendar



# on:
#   push:
#     tags:
#       - '*'
#     branches:
#       - '*'

# jobs:
#   run_tests:
#     runs-on: [ubuntu-22.04]
#     steps:
#       - uses: actions/checkout@main
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '16.18.0'
#           architecture: 'x64'
#       - name: Install express
#         run: npm install express --save
#       - name: Install SQLite
#         run: npm install sqlite3

#   build_and_pub:
#     needs: [run_tests]
#     runs-on: [ubuntu-22.04]
#     env:
#       LOGIN: ${{ secrets.DOCKER_LOGIN }}
#       NAME: ${{ secrets.DOCKER_NAME }}
#       PWD: ${{ secrets.DOCKER_PWD }}
#     steps:
#       - name: Login to docker.io
#         run: echo "$env:PWD" | docker login -u "$env:LOGIN" --password-stdin
#       - uses: actions/checkout@main
#       - name: Build image
#         run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
#       - name: Push image to docker.io
#         run: docker push $LOGIN/$NAME:${GITHUB_REF:11}