name: Publish on Docker Hub

on:
  push:
    branches:
      - "main"

jobs:
  post:
    runs-on: self-hosted
    steps:
    - name: delete folder
      run: rm -r calendar
    - name: copy file 
      run: git clone https://github.com/lenochcados/calendar.git
    - name: cd calendar
      run: cd calendar/
    - name: Delete docker container
      run: docker container kill $(docker container ls -q)
    - name: Delete docker image
      run: docker image prune
    - name: Docker clean
      run: docker system prune -a
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PWD}}  
    - name: docker build
      run:  docker build ~/actions-runner/_work/calendar/calendar/calendar -t lenochcados/calendar
    - name: docker run
      run: docker run -d -p 80:3000 lenochcados/calendar